name: Sync with Upstream (Rebase)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
env:
  UPSTREAM_REPO: 'hrsh7th/nvim-gtd'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Rebase from upstream
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add upstream "https://github.com/${{ env.UPSTREAM_REPO }}.git"
          git fetch upstream
          BRANCH_NAME=${{ github.ref_name }}
          echo "Rebasing local branch '$BRANCH_NAME' onto 'upstream/$BRANCH_NAME'..."
          git rebase upstream/$BRANCH_NAME
          echo "Force-pushing to origin..."
          git push origin $BRANCH_NAME --force
